repeat_mapbox.settings:
  type: config_object
  label: 'Mapbox settings'
  mapping:
    token:
      type: string
      label: 'Mapbox Access Token'
    url:
      type: string
      label: 'Mapbox map url'
