<?php

/**
 * @file
 * Provides map related functionality.
 */

declare(strict_types = 1);

/**
 * Implements hook_preprocess_HOOK().
 */
function repeat_mapbox_countries_preprocess_paragraph(array &$vars): void {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $vars['paragraph'];
  if ($paragraph->getType() === 'mapbox_map') {
    if (Drupal::config('repeat_mapbox.settings')->get('token')) {
      $vars['#attached']['library'][] = 'repeat_mapbox_countries/countries_hover';
    }
  }
}
